package com.kaiburr.taskapi.model;

import lombok.*;
import java.util.Date;

/**
 * TaskExecution class stores the details of a task run.
 * It contains the start and end times of the execution,
 * and the output generated by running the task's command.
 */

@Data                   // Generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor      // Creates a no-argument constructor
@AllArgsConstructor     // Creates a constructor with all fields
public class TaskExecution {

    private Date startTime;  // When the task execution started

    private Date endTime;    // When the task execution finished

    private String output;   // Output of the shell command executed
}
